"""add_clerk_id_to_user

Revision ID: ba7dfadb4b4d
Revises: c7b63a1cbbfb
Create Date: 2026-06-03 20:25:12.048226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7dfadb4b4d'
down_revision: Union[str, Sequence[str], None] = 'c7b63a1cbbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    
    # Set clerk_id to a temporary value for existing users
    op.execute("UPDATE users SET clerk_id = 'temp_' || id::text WHERE clerk_id IS NULL")
    
    # Make clerk_id NOT NULL
    op.alter_column('users', 'clerk_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###
